### ISSUE TITLE
Problem when launching TSEMO_Example

### ISSUE THREAD

**Issue by Theo3199** [Eric-Bradford/TS-EMO#4]
" Unable to perform assignment because the size of the left side is 1-by-3 and the size of the right side is 1-by-2 

Error in TSEMO_Example (line 25)
    Y(k,:) = f(X(k,:));                 % calculation of response data

"

**Comment by Eric-Bradford** [comment]
Thanks for your comment. I was running an example with 3 outputs and forgot to change it back. Either download TSEMO_Example again or change "no_outputs" in line 14 to 2, since "vlmop2" has 2 objectives.
