### ISSUE TITLE
little list of errors

### ISSUE THREAD

**Issue by Theo3199** [Eric-Bradford/TS-EMO#6]
Something new :
I tried to launch it using f@vlmop2 and I have had these issues:
'InvChov(A)' doesn't exist (TSEMO_V4) : I changed it for inv(chol(A)) and now it works.
However, I now have 
"
Error using mvnrnd (line 112)
SIGMA must be a symmetric positive semi-definite matrix.

"
Do you know where it could come from ? Thanks !

**Comment by Eric-Bradford** [comment]
Did you add the folder with subfolders? It seems like it is unable to find the functions from TS-EMO/Mex_files/... 

Also invChov finds the inverse of the full matrix, not of the Cholesky, i.e. InvChov(A) = inv(A). It just uses the cholesky decomposition, since it is faster and more accurate.
