### ISSUE TITLE
icudt61.dll required

### ISSUE THREAD

**Issue by ghost** [Eric-Bradford/TS-EMO#7]
starting the TSEMO Example, I get the following error

"....TS-EMO-master\Mex_files\invchol\invChol.mexw64': Missing dependent shared
libraries:
'icudt61.dll' required by"
'....\Mex_files\invchol\invChol.mexw64'

Can you help me with this or is this rather a problem of my Matlab version (19a) ?

**Comment by Eric-Bradford** [comment]
The Matlab version is fine. If I had to make an educated guess, you might be running 32 bit Matlab? Either way try one of the following that should fix it:

1. Compile the mex file yourself, then the dependable files will suit your system. In the same folder you can find "invChol_mex.c". Just follow the steps on the Matlab website to compile this file (https://www.mathworks.com/help/matlab/ref/mex.html), I think it is just "mex invChol_mex.c". Once compiled, simply rename the new file to "invChol" and delete the previous file (invChol.mexw64).   

2. Just delete the file "invChol.mexw64", then Matlab will use the .m file instead (invChol.m). This is an easier solution, but it will be slightly slower than using the .mex file.

**Comment by ghost** [comment]
I tried your 2. solution and it worked! Thanks a lot!
